/**
 * Commercial photoshoot gallery (public/gallery/photoshoot/{thumb,full}/).
 * THIS FILE IS GENERATED by media-staging/gen_gallery.sh — do not hand-edit entries.
 */
export type GalleryPhoto = { f: string; w: number; h: number };

export const PHOTOSHOOT_PHOTOS: GalleryPhoto[] = [];
