-- 2026-08-05: Season 5 (BCPL 4) schedule catch-up — idempotent, safe to rerun every deploy
-- Teams (skip if already present by season+slug), then 23 matches (unique on season+match_no).
-- Season 5 (BCPL 4) teams — idempotent
INSERT INTO teams (season, slug, name, city, color, second_color) SELECT 5, 'rajasthan-scorchers', 'Rajasthan Scorchers', 'Jaipur', '#E97B6B', '#F5A623' WHERE NOT EXISTS (SELECT 1 FROM teams WHERE season=5 AND slug='rajasthan-scorchers');
INSERT INTO teams (season, slug, name, city, color, second_color) SELECT 5, 'punjab-warriors', 'Punjab Warriors', 'Chandigarh', '#DC2626', '#1D4ED8' WHERE NOT EXISTS (SELECT 1 FROM teams WHERE season=5 AND slug='punjab-warriors');
INSERT INTO teams (season, slug, name, city, color, second_color) SELECT 5, 'kolkata-tigers', 'Kolkata Tigers', 'Kolkata', '#F97316', '#7C3AED' WHERE NOT EXISTS (SELECT 1 FROM teams WHERE season=5 AND slug='kolkata-tigers');
INSERT INTO teams (season, slug, name, city, color, second_color) SELECT 5, 'lucknow-nawabs', 'Lucknow Nawabs', 'Lucknow', '#F59E0B', '#065F46' WHERE NOT EXISTS (SELECT 1 FROM teams WHERE season=5 AND slug='lucknow-nawabs');
INSERT INTO teams (season, slug, name, city, color, second_color) SELECT 5, 'mumbai-mavericks', 'Mumbai Mavericks', 'Mumbai', '#3B82F6', '#F59E0B' WHERE NOT EXISTS (SELECT 1 FROM teams WHERE season=5 AND slug='mumbai-mavericks');
INSERT INTO teams (season, slug, name, city, color, second_color) SELECT 5, 'hyderabad-hawks', 'Hyderabad Hawks', 'Hyderabad', '#16A34A', '#EF4444' WHERE NOT EXISTS (SELECT 1 FROM teams WHERE season=5 AND slug='hyderabad-hawks');
INSERT INTO teams (season, slug, name, city, color, second_color) SELECT 5, 'delhi-suryas', 'Delhi Suryas', 'Delhi', '#6366F1', '#F97316' WHERE NOT EXISTS (SELECT 1 FROM teams WHERE season=5 AND slug='delhi-suryas');
INSERT INTO teams (season, slug, name, city, color, second_color) SELECT 5, 'chennai-thalaivas', 'Chennai Thalaivas', 'Chennai', '#2563EB', '#F59E0B' WHERE NOT EXISTS (SELECT 1 FROM teams WHERE season=5 AND slug='chennai-thalaivas');
INSERT INTO teams (season, slug, name, city, color, second_color) SELECT 5, 'ahmedabad-lions', 'Ahmedabad Lions', 'Ahmedabad', '#B91C1C', '#F59E0B' WHERE NOT EXISTS (SELECT 1 FROM teams WHERE season=5 AND slug='ahmedabad-lions');
INSERT INTO teams (season, slug, name, city, color, second_color) SELECT 5, 'bengaluru-rockets', 'Bengaluru Rockets', 'Bengaluru', '#EF4444', '#1D4ED8' WHERE NOT EXISTS (SELECT 1 FROM teams WHERE season=5 AND slug='bengaluru-rockets');

-- Matches
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (1, 5, 'Chennai Thalaivas', 'Mumbai Mavericks', 'TBA', '2026-09-26 14:00:00+00'::timestamptz, 'scheduled', 'league', 'A') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (2, 5, 'Delhi Suryas', 'Kolkata Tigers', 'TBA', '2026-09-27 10:00:00+00'::timestamptz, 'scheduled', 'league', 'B') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (3, 5, 'Bengaluru Rockets', 'Punjab Warriors', 'TBA', '2026-09-27 14:00:00+00'::timestamptz, 'scheduled', 'league', 'B') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (4, 5, 'Lucknow Nawabs', 'Delhi Suryas', 'TBA', '2026-09-28 10:00:00+00'::timestamptz, 'scheduled', 'league', 'B') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (5, 5, 'Ahmedabad Lions', 'Chennai Thalaivas', 'TBA', '2026-09-28 14:00:00+00'::timestamptz, 'scheduled', 'league', 'A') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (6, 5, 'Kolkata Tigers', 'Bengaluru Rockets', 'TBA', '2026-09-29 10:00:00+00'::timestamptz, 'scheduled', 'league', 'B') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (7, 5, 'Mumbai Mavericks', 'Rajasthan Scorchers', 'TBA', '2026-09-29 14:00:00+00'::timestamptz, 'scheduled', 'league', 'A') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (8, 5, 'Hyderabad Hawks', 'Ahmedabad Lions', 'TBA', '2026-09-30 10:00:00+00'::timestamptz, 'scheduled', 'league', 'A') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (9, 5, 'Punjab Warriors', 'Lucknow Nawabs', 'TBA', '2026-09-30 14:00:00+00'::timestamptz, 'scheduled', 'league', 'B') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (10, 5, 'Chennai Thalaivas', 'Rajasthan Scorchers', 'TBA', '2026-10-01 10:00:00+00'::timestamptz, 'scheduled', 'league', 'A') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (11, 5, 'Bengaluru Rockets', 'Lucknow Nawabs', 'TBA', '2026-10-01 14:00:00+00'::timestamptz, 'scheduled', 'league', 'B') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (12, 5, 'Kolkata Tigers', 'Punjab Warriors', 'TBA', '2026-10-02 10:00:00+00'::timestamptz, 'scheduled', 'league', 'B') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (13, 5, 'Mumbai Mavericks', 'Hyderabad Hawks', 'TBA', '2026-10-02 14:00:00+00'::timestamptz, 'scheduled', 'league', 'A') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (14, 5, 'Ahmedabad Lions', 'Rajasthan Scorchers', 'TBA', '2026-10-03 10:00:00+00'::timestamptz, 'scheduled', 'league', 'A') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (15, 5, 'Delhi Suryas', 'Bengaluru Rockets', 'TBA', '2026-10-03 14:00:00+00'::timestamptz, 'scheduled', 'league', 'B') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (16, 5, 'Kolkata Tigers', 'Lucknow Nawabs', 'TBA', '2026-10-04 10:00:00+00'::timestamptz, 'scheduled', 'league', 'B') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (17, 5, 'Chennai Thalaivas', 'Hyderabad Hawks', 'TBA', '2026-10-04 14:00:00+00'::timestamptz, 'scheduled', 'league', 'A') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (18, 5, 'Mumbai Mavericks', 'Ahmedabad Lions', 'TBA', '2026-10-05 10:00:00+00'::timestamptz, 'scheduled', 'league', 'A') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (19, 5, 'Delhi Suryas', 'Punjab Warriors', 'TBA', '2026-10-05 14:00:00+00'::timestamptz, 'scheduled', 'league', 'B') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (20, 5, 'Rajasthan Scorchers', 'Hyderabad Hawks', 'TBA', '2026-10-06 14:00:00+00'::timestamptz, 'scheduled', 'league', 'A') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (21, 5, 'Group A (1st)', 'Group B (2nd)', 'TBA', '2026-10-08 14:00:00+00'::timestamptz, 'scheduled', 'semifinal', '') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (22, 5, 'Group B (1st)', 'Group A (2nd)', 'TBA', '2026-10-09 14:00:00+00'::timestamptz, 'scheduled', 'semifinal', '') ON CONFLICT (season, match_no) DO NOTHING;
INSERT INTO matches (match_no, season, team1, team2, venue, scheduled_at, status, stage, grp) VALUES (23, 5, 'Winner SF1', 'Winner SF2', 'TBA', '2026-10-10 14:00:00+00'::timestamptz, 'scheduled', 'final', '') ON CONFLICT (season, match_no) DO NOTHING;
